### PR TITLE
[feat] Shell Scriprt to install git-conform

### PR DESCRIPTION
**Pull request by Abdogouhmad**
# What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 This pull request introduces a new shell script for installing the **git-conform** to `/usr/bin/` and uninstalling the `git-conform` CLI, and updates the `README.md` to include instructions for using this script.  

> [!IMPORTANT]  
> Please check the readme instruction if I am correctly referring to the raw of the installation content. However, the script works fine.

Overall, Nice work.

### CODE REVIEW

**Review by j3dr — CHANGES_REQUESTED** [review]
It would be better to download the binary using the **latest** tag instead of a specific one (like **v0.1.0** in this case), so we don't have to edit the script everytime there's a new release :wink: Please change the URL to `https://github.com/ndr3www/git-conform/releases/download/latest/git-conform`
## https://github.com/ndr3www/git-conform/blob/3154b8036f86f59f22a3fd19ab49998da35c1814/install#L15

Also, here I think it would be nice to remove the app directory in `~/.local/share` as well
## https://github.com/ndr3www/git-conform/blob/3154b8036f86f59f22a3fd19ab49998da35c1814/install#L20-L24

**Comment by j3dr** [comment]
Anyway, nice work likewise and thank you for contributing!

**Comment by Abdogouhmad** [comment]
quick question do you store any specific data within `~/.local/share` ?

**Comment by j3dr** [comment]
Yup, the file containing entries of tracked repositories is located in `~/.local/share/git-conform`

**Comment by Abdogouhmad** [comment]
Fixed now check the script of the last commit.

**Review by j3dr — APPROVED** [review]

**Pull request merged**
